### ISSUE TITLE
minor: rename variables to be more informative

### ISSUE THREAD

**Issue by Ram-N** [mine-cetinkaya-rundel/ds-ed-enar2018#6]
![image](https://user-images.githubusercontent.com/737241/38002421-16b3608c-31e7-11e8-828a-2666aa246dc2.png)

This is really minor. (Or maybe I misunderstood). In the Bike rental example, when you create a tibble to look for why one day in "Winter" there were so many rentals, instead of calling the variable `min` if you renamed it to `max` and `day_max` it would be easier to follow. I suspect this is cut-and-paste from the example when you did indeed look for `min.`

**Comment by mine-cetinkaya-rundel** [comment]
Indeed that's a typo, thanks! Fixed by fbd265d0742ff2c41b4b47af8b5cda9324c89f41
